include ../Makefile.inc

all : memtester/memtester

memtester/memtester :
	echo "SKIPPING MEMTESTER"

install : memory-test.sh memtester/memtester
	echo "SKIPPING MEMTESTER"

clean :
	$(MAKE) -C memtester clean
